#twork whith string
print('hello word')
message = 'Bobby\'s world'
print(message)
print(len(message))
print(message[0])
print(message[0:5])
print(message.lower())
print(message.upper())
print(message.count('b'))
print(message.find('world'))
new_message = message.replace('world','Universe')
print(new_message)
somaString = new_message +' '+ message
print(somaString) 
somaString = '{} and {}, welcome'.format(message,new_message)
print(somaString) 
print(dir(message))
#print(help(str))
print(help(str.lower))